# Generated by Django 5.1.7 on 2025-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="color",
            field=models.CharField(
                choices=[
                    ("#c02c38", "Ruby"),
                    ("#2ecc71", "Emerald"),
                    ("#3498db", "Sapphire"),
                    ("#e6b32e", "Amber"),
                    ("#9b59b6", "Violet"),
                    ("#e67e22", "Coral"),
                    ("#e84393", "Rose"),
                    ("#34495e", "Slate"),
                    ("#f5f5f0", "Ivory"),
                    ("#bdc3c7", "Silver"),
                    ("#16a085", "Teal"),
                    ("#e74c3c", "Crimson"),
                    ("#967bb6", "Lavender"),
                    ("#00b894", "Mint"),
                    ("#5352ed", "Indigo"),
                    ("#fbc531", "Honey"),
                ],
                default="#3498db",
                help_text="User's color preference",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pronoun",
            field=models.CharField(
                blank=True, help_text="User's pronoun", max_length=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                help_text="User's theme preference",
                max_length=6,
            ),
        ),
    ]
